# Generated by Django 6.1.1 on 2026-09-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='secondary_course',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
